version: '3'
services:
  db:
    container_name: mysql
    build:
      context: ./
      dockerfile: docker/db/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
  app:
    user: 0:0
    container_name: backend
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    working_dir: /var/www/
    restart: always
    volumes:
      - ./:/var/www/
      - ./docker/app/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db
  web:
    container_name: nginx
    hostname: laravel.localhost
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app
